version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgress
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=passchunkitappdb
    volumes:
      - ./docker/postgress/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./static/:/static