version: '3'

services:
  db:
    build:
      context: .
    volumes:
      - ./data/db:/vol/web/data
      - ./db.sqlite3:/vol/web/db.sqlite3
    environment:
      - SQLITE3_DB=db.sqlite3

  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static/media/sentence/:/vol/static/media/sentence/
      - static-data:/vol/static
      - proxy-dhparams:/vol/proxy
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    environment:
      - APP_HOST=app
      - APP_PORT=9000

  certbot:
    build:
      context: ./proxy/certbot
    command: echo "Pooping..."
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - proxy

volumes:
  static-data:
  certbot-web:
  proxy-dhparams:
  certbot-certs: