# Generated by Django 3.2 on 2021-07-29 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('education', models.CharField(choices=[('Primary school', 'Primary school'), ('Lower secondary school', 'Lower secondary school'), ('Upper secondary school, upper secondary school graduate, or vocational education graduate', 'Upper secondary school, upper secondary school graduate, or vocational education graduate'), ('Polytechnic degree', 'Polytechnic degree'), ('University degree: BA or equivalent', 'University degree: BA or equivalent'), ('University degree: MA or equivalent', 'University degree: MA or equivalent'), ('University degree: Ph.D. or equivalent', 'University degree: Ph.D. or equivalent')], max_length=1000)),
                ('major', models.TextField(default='none', max_length=1000)),
                ('native_language', models.TextField(default='nothing')),
                ('other_language', models.TextField(default='nothing')),
                ('dyslexia', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('hearing_diff', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('whisper', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('comments', models.TextField(default='nothing')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('instructions', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('doing', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('simple', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('demanding', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('pessure', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('fun', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('reflects', models.CharField(choices=[('Strongly agree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=25)),
                ('performance', models.CharField(choices=[('Poor', 'Poor'), ('Satisfactory', 'Satisfactory'), ('Good', 'Good'), ('Very good', 'Very good')], max_length=25)),
                ('understood', models.CharField(choices=[('All the time', 'all the time'), ('Most of the time', 'most of the time'), ('Some of the time', 'some of the time'), ('Very little time', 'very little time'), ('Not at all', 'not at all')], max_length=25)),
                ('measured', models.TextField(default='nothing')),
                ('strategy', models.TextField(default='nothing')),
                ('impression', models.TextField(default='nothing')),
                ('comments', models.TextField(default='nothing')),
            ],
        ),
        migrations.CreateModel(
            name='sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='nothing')),
                ('index', models.IntegerField()),
                ('session_key', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40)),
                ('session_key', models.TextField(default='nothing')),
                ('ip', models.CharField(max_length=400)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('prolific_id', models.CharField(max_length=100)),
                ('study_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('checkbox', models.TextField(default='nothing')),
                ('index', models.IntegerField()),
                ('question', models.CharField(max_length=10)),
            ],
        ),
    ]
