# Generated by Django 3.2 on 2021-08-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0002_experement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='experement_data',
            name='prolific',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experement_data',
            name='questions',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experement_data',
            name='sentences',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
