# Generated by Django 3.2 on 2021-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0005_auto_20211020_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='draft_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameExperement', models.TextField()),
                ('numberOfExtracts', models.TextField()),
                ('ImitationTask', models.BooleanField()),
                ('UseQuestions', models.BooleanField()),
                ('UseProlific', models.BooleanField()),
                ('linkToProlific', models.TextField()),
                ('helloExample', models.TextField()),
                ('consentExample', models.TextField()),
                ('outlineExample', models.TextField()),
                ('backgroundExample', models.TextField()),
                ('backgroundAddQ', models.TextField()),
                ('feedbackExample', models.TextField()),
                ('feedbackAddQ', models.TextField()),
                ('goodbyeExample', models.TextField()),
            ],
        ),
    ]
