# Generated by Django 3.2 on 2021-11-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0006_draft_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft_data',
            old_name='consentExample',
            new_name='consentEditor',
        ),
        migrations.RenameField(
            model_name='draft_data',
            old_name='goodbyeExample',
            new_name='goodbyeEditor',
        ),
        migrations.RenameField(
            model_name='draft_data',
            old_name='helloExample',
            new_name='helloEditor',
        ),
        migrations.RenameField(
            model_name='draft_data',
            old_name='outlineExample',
            new_name='outlineEditor',
        ),
    ]
