# Generated by Django 3.1.3 on 2021-11-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0008_auto_20211118_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft_data',
            old_name='audio',
            new_name='uploadPracticeAudio',
        ),
    ]
