# Generated by Django 3.1.3 on 2021-11-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0009_auto_20211118_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='uploadPracticeTranscripts',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
