# Generated by Django 3.1.3 on 2021-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0010_draft_data_uploadpracticetranscripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='uploadExperementAudio',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft_data',
            name='uploadExperementTranscripts',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
