# Generated by Django 3.1.3 on 2021-11-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0011_auto_20211127_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='nameExperementForParticipants',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
