# Generated by Django 3.1.3 on 2021-11-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0012_draft_data_nameexperementforparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='experimentInstructions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft_data',
            name='practiceInstructions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
