# Generated by Django 3.1.3 on 2021-11-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0013_auto_20211127_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='addedQ',
            field=models.TextField(default='nothing'),
        ),
    ]
