# Generated by Django 3.1.3 on 2021-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0014_background_addedq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='addedQ',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='dyslexia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='hearing_diff',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='major',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='native_language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='other_language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='session_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='sex',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='whisper',
            field=models.TextField(),
        ),
    ]
