# Generated by Django 3.1.3 on 2021-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0015_auto_20211130_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='audiosExperement',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft_data',
            name='audiosPractice',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='demanding',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='doing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fun',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='impression',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='measured',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='performance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pessure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reflects',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='session_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='simple',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='strategy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='understood',
            field=models.TextField(),
        ),
    ]
