# Generated by Django 3.1.3 on 2021-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0016_auto_20211201_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='uploadExperimentTranscriptsData',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft_data',
            name='uploadPracticeTranscriptsData',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
