# Generated by Django 3.1.3 on 2021-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0018_test_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='addedQ',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
