# Generated by Django 3.1.3 on 2021-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0020_experiment_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.TextField(default='nothing'),
        ),
    ]
