# Generated by Django 3.1.3 on 2022-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0022_background_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='usertoken',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
