# Generated by Django 3.1.3 on 2022-01-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0023_draft_data_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft_data',
            old_name='usertoken',
            new_name='access_token',
        ),
    ]
