# Generated by Django 3.1.3 on 2022-01-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0024_auto_20220123_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft_data',
            old_name='access_token',
            new_name='accessToken',
        ),
    ]
