# Generated by Django 3.1.3 on 2022-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0025_auto_20220123_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='newField',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
