# Generated by Django 3.1.3 on 2022-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0027_experiment_links_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='experiment_name',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='experiment_name',
            field=models.TextField(default='nothing'),
        ),
    ]
