# Generated by Django 3.1.3 on 2022-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0028_auto_20220127_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='prolific_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
