# Generated by Django 3.1.3 on 2022-01-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0030_auto_20220128_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft_data',
            old_name='numberOfExtracts',
            new_name='shuffleExtracts',
        ),
        migrations.AddField(
            model_name='draft_data',
            name='shuffleExtractsPractice',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
