# Generated by Django 3.1.3 on 2022-02-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0031_auto_20220131_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='age',
            new_name='AcadmicField',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='comments',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='dyslexia',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='education',
            new_name='Dyslexsia',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='hearing_diff',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='major',
            new_name='HearingDiff',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='native_language',
            new_name='LevelEducation',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='other_language',
            new_name='NativeLanguage',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='sex',
            new_name='OtherLanguage',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='whisper',
            new_name='Whisper',
        ),
    ]
