# Generated by Django 3.1.3 on 2022-04-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0033_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
