# Generated by Django 3.1.3 on 2022-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0036_auto_20220426_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft_data',
            name='experiment_link',
        ),
        migrations.RemoveField(
            model_name='draft_data',
            name='experiment_stopped',
        ),
        migrations.AddField(
            model_name='experiment_links',
            name='experiment_stopped',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
