# Generated by Django 3.1.3 on 2022-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0037_auto_20220426_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='date',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='experiment_links',
            name='experiment_start_time',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='date',
            field=models.TextField(default='nothing'),
        ),
    ]
