# Generated by Django 3.1.3 on 2022-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0038_auto_20220731_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_data',
            name='sessionTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
