# Generated by Django 3.1.3 on 2022-08-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0039_draft_data_sessiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft_data',
            name='sessionTime',
            field=models.IntegerField(default=90),
        ),
    ]
