# Generated by Django 3.1.3 on 2022-08-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkitapp', '0040_auto_20220808_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft_data',
            old_name='uploadExperementAudio',
            new_name='uploadExperimentAudio',
        ),
        migrations.RenameField(
            model_name='draft_data',
            old_name='uploadExperementTranscripts',
            new_name='uploadExperimentTranscripts',
        ),
    ]
